version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      DB_HOST: mysqlapi
      DB_USER: root
      DB_PASSWORD: rootpassword
      DB_NAME: backend_cloud
    depends_on:
      - mysqlapi
    networks:
      - app_network
    volumes:
      - app_data:/usr/src/app

  mysqlapi:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    container_name: mysqlapi
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: backend_cloud
      MYSQL_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - init_sql_data:/docker-entrypoint-initdb.d
    networks:
      - app_network

networks:
  app_network:

volumes:
  app_data:
    name: app_volume
  db_data:
    name: mysql_data
  init_sql_data:
    name: init_sql_volume
