version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_container
    ports:
      - "4000:4000"
    environment:
      - DB_HOST=localhost
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=backend_cloud
      - DB_PORT=3306
    depends_on:
      - mysql
    restart: always
    volumes:
      - .:/app # Monta el código fuente para desarrollo

  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: backend_cloud
      MYSQL_USER: root
      MYSQL_PASSWORD: rootpassword
    volumes:
      - mysql_data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d

volumes:
  mysql_data:
